# Generated by Django 4.2.4 on 2023-08-18 09:43

from django.db import migrations, models
import django.db.models.deletion
import sfbk.models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=sfbk.models.event_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='pkey',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/%(link)s/}')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfbk.event')),
            ],
        ),
    ]
