# Generated by Django 4.2.4 on 2023-08-18 09:50

from django.db import migrations, models
import sfbk.models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbk', '0002_event_iscompleted_event_thumb_alter_event_pkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to=sfbk.models.EventImage.upload_to_path),
        ),
    ]
