# Generated by Django 4.2.4 on 2023-08-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbk', '0005_rename_entry_fee_event_entryfee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
