# Generated by Django 4.2.4 on 2023-08-19 23:35

from django.db import migrations, models
import django.db.models.deletion
import sfbk.models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbk', '0006_alter_event_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(blank=True, max_length=100, null=True)),
                ('dp', models.ImageField(upload_to=sfbk.models.EventSpeaker.upload_to_path)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sfbk.event')),
            ],
        ),
    ]
