# Generated by Django 4.2.4 on 2023-08-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfbk', '0007_eventspeaker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventspeaker',
            old_name='speaker',
            new_name='name',
        ),
    ]
