# Generated by Django 4.2.4 on 2023-08-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbk', '0009_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(default='AI', max_length=500),
            preserve_default=False,
        ),
    ]
