# Generated by Django 4.2.4 on 2023-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('isPrivate', models.BooleanField(default=False)),
                ('pkey', models.CharField(max_length=32)),
                ('hasFee', models.BooleanField(default=True)),
                ('entry_fee', models.IntegerField(blank=True, null=True)),
                ('host', models.CharField(max_length=500)),
            ],
        ),
    ]
